name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

env:
  JAVA_VERSION: '17'
  NODE_VERSION: '18'

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: maven

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      shell: bash
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm run test --if-present -- --coverage --watchAll=false

    - name: Run Frontend Lint
      working-directory: ./frontend
      run: npm run lint --if-present

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build --if-present

    - name: Run Backend Tests
      run: mvn clean test -Dspring.profiles.active=test

    - name: Generate Test Coverage Report
      run: mvn jacoco:report

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./target/site/jacoco/jacoco.xml,./frontend/coverage/lcov.info
        flags: backend,frontend
        name: schedbank-coverage
        fail_ci_if_error: false

  security-scan:
    name: Security Analysis
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'schedbank'
        path: '.'
        format: 'ALL'
        
    - name: Upload OWASP Results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: reports/dependency-check-report.sarif

    - name: Run Snyk Security Scan
      uses: snyk/actions/maven@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      if: ${{ env.SNYK_TOKEN != '' }}
      with:
        args: --severity-threshold=high

  quality-gate:
    name: Code Quality Gate
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: maven

    - name: SonarCloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: ${{ env.SONAR_TOKEN != '' }}
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=razecmarketing_schedbank \
          -Dsonar.organization=razecmarketing \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
          -Dsonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [test, security-scan, quality-gate]
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: maven

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Build Frontend
      working-directory: ./frontend
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
        npm run build --if-present

    - name: Build Backend
      run: mvn clean package -DskipTests

    - name: Build Docker Image
      run: |
        docker build -t schedbank:${{ github.sha }} .
        docker tag schedbank:${{ github.sha }} schedbank:latest

    - name: Run Security Scan on Docker Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'schedbank:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy Results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    environment: staging
    
    steps:
    - name: Deploy to Staging Environment
      run: |
        echo "Deploying to staging environment..."
        # Add deployment scripts here

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      if: ${{ env.AWS_ACCESS_KEY_ID != '' && env.AWS_SECRET_ACCESS_KEY != '' }}
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to EKS Cluster
      if: ${{ env.AWS_ACCESS_KEY_ID != '' && env.AWS_SECRET_ACCESS_KEY != '' }}
      run: |
        aws eks update-kubeconfig --name schedbank-prod-cluster
        kubectl apply -f k8s/
        kubectl rollout status deployment/schedbank-app -n schedbank-prod --timeout=300s

    - name: Run Production Health Checks
      if: ${{ env.AWS_ACCESS_KEY_ID != '' && env.AWS_SECRET_ACCESS_KEY != '' }}
      run: |
        # Wait for deployment to be ready
        sleep 60
        # Health check
        curl -f https://api.schedbank.com/actuator/health || exit 1
        # Performance test
        curl -f https://api.schedbank.com/actuator/metrics || exit 1

    - name: Notify Team
      uses: 8398a7/action-slack@v3
      if: ${{ env.SLACK_WEBHOOK_URL != '' }}
      with:
        status: ${{ job.status }}
        text: "SchedBank Production Deployment: ${{ job.status }}"
      env:
        SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}

  performance-test:
    name: Performance Testing
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - name: Run Load Tests
      id: k6
      uses: grafana/k6-action@v0.2.0
      continue-on-error: true
      with:
        filename: tests/performance/load-test.js
        flags: --out json=results.json

    - name: Upload Performance Results
      if: steps.k6.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: performance-results
        path: results.json

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run OWASP ZAP Security Scan
      uses: zaproxy/action-full-scan@v0.8.0
      continue-on-error: true
      with:
        target: 'http://localhost:8080'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'